name: Continuous Deploy
on: push

jobs:
  build-job:
    name: build job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Run a one-line script
        run: echo Hello, world!
        
      # - name: Build and Deploy
      #   run: |
      #     npm install
      #     npm run build --if-present
      #   env:
      #     CI: true