name: Continuous Deploy
on:
  push:
    branches:
      - master

jobs:
  build-job:
    name: build job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # - name: Use Node.js 10.x
      #   uses: actions/setup-node@v1
      #   with:
      #   node-version: 10.x

      - name: Run a one-line script
        run: echo Hello, worlds!

      - name: Install and Build
        run: |
          npm install
          npm run build

      # react项目的FOLDER为build，vue项目改为dist
      - name: Deploy
        uses: Linosau/react-music@master
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          BUILD_SCRIPT: npm install && npm run build
